name = "coach-pedro-ai"
main = "src/index.js"
compatibility_date = "2025-05-30"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "PUSH_KV"
id = "96139c40523448939c29acf202c4ff16"

[vars]
VAPID_EMAIL = "mailto:pedro@example.com"
